default['pathIM']="home/ibm/IM"
default['pathWas']="home/ibm/WAS"
default['ibm']="home/ibm"
default['unzip']['im']="/home/InstalMgr1.6.2_LNX_X86_64_WAS_8.5.5.zip"
default['install']="/home/ibm/IM/installc"
default['unzip']['p1']="/home/WAS_V8.5_1_OF_3.zip"
default['unzip']['p2']="/home/WAS_V8.5_2_OF_3.zip"
default['unzip']['p3']="/home/WAS_V8.5_3_OF_3.zip"
default['appsrv']="/opt/IBM/WebSphere/AppServer"
default['imanger']=" /opt/IBM/InstallationManager/IMShared"
default['wasversion']="com.ibm.websphere.BASE.v85"
default['profile']['name']="nodeProfile"
default['profile']['node']="cell01"
default['profile']['host']="localhost"
default['profile']['admin']['name']="wasadmin"
default['profile']['admin']['pass']="wasadmin"

